version: "2"

services:
  api-users:
    image: "houssemsalemp/titane-api-members:latest"
    container_name: api-members-titane
    ports:
      - 8090:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  api-books:
    image: "houssemsalemp/titane-api-books:latest"
    container_name: api-books-titane
    ports:
      - 8080:8081
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  desktop:
    image: houssemsalemp/titane-desktop:latest
    container_name: desktop
    ports:
      - 80:80

  db:
    image: "postgres:alpine"
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
